framework: mock
input_neurons: 0
hidden_layers: [128, 64, 16]
output_neurons: 2
neuron_type: lif
learning_rate: 0.001
epochs: 10
batch_size: 32
validation_split: 0.2
dt: 0.001
simulation_time: 1.0
encoding_method: rate
model_name: snn_security_model
save_checkpoints: true
export_format: standard

